###
http://localhost:3000/todos/

###
http://localhost:3000/agenda/?date=2020-9-22

###
http://localhost:3000/todos/?priority=HIGH


###
POST http://localhost:3000/todos/
Content-Type : application/json 

{
  "id": 6,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TODO",
  "category": "HOME",
  "dueDate": "2021-2-22"
}

###
PUT http://localhost:3000/todos/3/
Content-Type : application/json

{
      "status": "DONE"
    }

###

DELETE http://localhost:3000/todos/6/
